// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8apFji3Q2zH30jZBKzOLU-E_Qw20rLNc',
    appId: '1:533140308687:web:3686b2a74cc0f3f11b2dba',
    messagingSenderId: '533140308687',
    projectId: 'fyp-22205349',
    authDomain: 'fyp-22205349.firebaseapp.com',
    databaseURL: 'https://fyp-22205349-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-22205349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwuRSUlAQwyFsKQ9buMkV90oVQu5yo-E',
    appId: '1:533140308687:android:d87d3fd345530c161b2dba',
    messagingSenderId: '533140308687',
    projectId: 'fyp-22205349',
    databaseURL: 'https://fyp-22205349-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-22205349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDouUHXJ1oFM_Y6biOWNiARgrb6IlUifXw',
    appId: '1:533140308687:ios:83da0ce26b3e184d1b2dba',
    messagingSenderId: '533140308687',
    projectId: 'fyp-22205349',
    databaseURL: 'https://fyp-22205349-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-22205349.appspot.com',
    iosBundleId: 'com.example.fyp22205349',
  );
}
